-- 1. Tabela: Hospital
CREATE TABLE public.hospital (
    id_hospital INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    endereco VARCHAR(255),
    telefone VARCHAR(20),
    email VARCHAR(150),
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 2. Tabela: Paciente
CREATE TABLE public.paciente (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    data_nascimento DATE,
    telefone VARCHAR(20),
    tipo_sanguineo VARCHAR(5),
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 3. Tabela: Médico
CREATE TABLE public.medico (
    id_medico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital INTEGER NOT NULL,
    crm VARCHAR(20) NOT NULL UNIQUE,
    especialidade VARCHAR(100),
    nome VARCHAR(150) NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT medico_id_hospital_fkey FOREIGN KEY (id_hospital)
        REFERENCES public.hospital(id_hospital)
);

-- 4. Tabela: Usuário
CREATE TABLE public.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    cargo VARCHAR(50),
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 5. Tabela: Cirurgia
CREATE TABLE public.cirurgia (
    id_cirurgia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    complexidade VARCHAR(30),
    tempo_estimado INTERVAL,
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 6. Tabela: Recurso
CREATE TABLE public.recurso (
    id_recurso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital INTEGER NOT NULL,
    nome VARCHAR(150) NOT NULL,
    categoria VARCHAR(100),
    quantidade INTEGER DEFAULT 0 NOT NULL,
    status VARCHAR(30),
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT recurso_id_hospital_fkey FOREIGN KEY (id_hospital)
        REFERENCES public.hospital(id_hospital)
);

-- 7. Tabela: Sala Cirúrgica
CREATE TABLE public.sala_cirurgica (
    id_sala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospital INTEGER NOT NULL,
    numero VARCHAR(10),
    tipo VARCHAR(50),
    status VARCHAR(30),
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT sala_cirurgica_id_hospital_fkey FOREIGN KEY (id_hospital)
        REFERENCES public.hospital(id_hospital)
);

-- 8. Tabela: Solicitação
CREATE TABLE public.solicitacao (
    id_solicitacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_solicitacao DATE DEFAULT CURRENT_DATE NOT NULL,
    prioridade VARCHAR(20),
    status VARCHAR(30),
    id_paciente INTEGER NOT NULL,
    id_medico INTEGER,
    id_hospital INTEGER NOT NULL,
    id_cirurgia INTEGER,
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT solicitacao_id_paciente_fkey FOREIGN KEY (id_paciente)
        REFERENCES public.paciente(id_paciente),
    CONSTRAINT solicitacao_id_medico_fkey FOREIGN KEY (id_medico)
        REFERENCES public.medico(id_medico),
    CONSTRAINT solicitacao_id_hospital_fkey FOREIGN KEY (id_hospital)
        REFERENCES public.hospital(id_hospital),
    CONSTRAINT solicitacao_id_cirurgia_fkey FOREIGN KEY (id_cirurgia)
        REFERENCES public.cirurgia(id_cirurgia)
);

-- 9. Tabela: Agendamento
CREATE TABLE public.agendamento (
    id_agendamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    hora TIME WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(30),
    id_solicitacao INTEGER NOT NULL,
    id_sala INTEGER NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT agendamento_id_solicitacao_fkey FOREIGN KEY (id_solicitacao)
        REFERENCES public.solicitacao(id_solicitacao),
    CONSTRAINT agendamento_id_sala_fkey FOREIGN KEY (id_sala)
        REFERENCES public.sala_cirurgica(id_sala),
    CONSTRAINT agendamento_sala_data_hora_key UNIQUE (id_sala, data, hora)
);

-- 10. Tabela: Cirurgia Recurso
CREATE TABLE public.cirurgia_recurso (
    id_cirurgia INTEGER NOT NULL,
    id_recurso INTEGER NOT NULL,
    quantidade_necessaria INTEGER DEFAULT 1 NOT NULL,
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT cirurgia_recurso_pkey PRIMARY KEY (id_cirurgia, id_recurso),
    CONSTRAINT cirurgia_recurso_id_cirurgia_fkey FOREIGN KEY (id_cirurgia)
        REFERENCES public.cirurgia(id_cirurgia),
    CONSTRAINT cirurgia_recurso_id_recurso_fkey FOREIGN KEY (id_recurso)
        REFERENCES public.recurso(id_recurso)
);
