--
-- PostgreSQL database dump
--

\restrict rfayAAausqHrSs43flSaIlUKnJGuYLIRlrwk6jdSPDpzwgewl6dUmcVJYLATqkh

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agendamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agendamento (
    id_agendamento integer NOT NULL,
    data date NOT NULL,
    hora time without time zone NOT NULL,
    status character varying(30),
    id_solicitacao integer NOT NULL,
    id_sala integer NOT NULL,
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.agendamento OWNER TO postgres;

--
-- Name: agendamento_id_agendamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.agendamento ALTER COLUMN id_agendamento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agendamento_id_agendamento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cirurgia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cirurgia (
    id_cirurgia integer NOT NULL,
    nome character varying(150) NOT NULL,
    descricao text,
    complexidade character varying(30),
    tempo_estimado interval,
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.cirurgia OWNER TO postgres;

--
-- Name: cirurgia_id_cirurgia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cirurgia ALTER COLUMN id_cirurgia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cirurgia_id_cirurgia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cirurgia_recurso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cirurgia_recurso (
    id_cirurgia integer NOT NULL,
    id_recurso integer NOT NULL,
    quantidade_necessaria integer DEFAULT 1 NOT NULL,
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.cirurgia_recurso OWNER TO postgres;

--
-- Name: hospital; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hospital (
    id_hospital integer NOT NULL,
    nome character varying(150) NOT NULL,
    cnpj character varying(18) NOT NULL,
    endereco character varying(255),
    telefone character varying(20),
    email character varying(150),
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.hospital OWNER TO postgres;

--
-- Name: hospital_id_hospital_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hospital ALTER COLUMN id_hospital ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hospital_id_hospital_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medico (
    id_medico integer NOT NULL,
    id_hospital integer NOT NULL,
    crm character varying(20) NOT NULL,
    especialidade character varying(100),
    nome character varying(150) NOT NULL,
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.medico OWNER TO postgres;

--
-- Name: medico_id_medico_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medico ALTER COLUMN id_medico ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medico_id_medico_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paciente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paciente (
    id_paciente integer NOT NULL,
    nome character varying(150) NOT NULL,
    cpf character varying(14) NOT NULL,
    data_nascimento date,
    telefone character varying(20),
    tipo_sanguineo character varying(5),
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.paciente OWNER TO postgres;

--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.paciente ALTER COLUMN id_paciente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paciente_id_paciente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recurso (
    id_recurso integer NOT NULL,
    id_hospital integer NOT NULL,
    nome character varying(150) NOT NULL,
    categoria character varying(100),
    quantidade integer DEFAULT 0 NOT NULL,
    status character varying(30),
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.recurso OWNER TO postgres;

--
-- Name: recurso_id_recurso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recurso ALTER COLUMN id_recurso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurso_id_recurso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sala_cirurgica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sala_cirurgica (
    id_sala integer NOT NULL,
    id_hospital integer NOT NULL,
    numero character varying(10),
    tipo character varying(50),
    status character varying(30),
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.sala_cirurgica OWNER TO postgres;

--
-- Name: sala_cirurgica_id_sala_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sala_cirurgica ALTER COLUMN id_sala ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sala_cirurgica_id_sala_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitacao (
    id_solicitacao integer NOT NULL,
    data_solicitacao date DEFAULT CURRENT_DATE NOT NULL,
    prioridade character varying(20),
    status character varying(30),
    id_paciente integer NOT NULL,
    id_medico integer,
    id_hospital integer NOT NULL,
    id_cirurgia integer,
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.solicitacao OWNER TO postgres;

--
-- Name: solicitacao_id_solicitacao_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitacao ALTER COLUMN id_solicitacao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitacao_id_solicitacao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    nome character varying(150) NOT NULL,
    cpf character varying(14) NOT NULL,
    email character varying(150) NOT NULL,
    senha character varying(255) NOT NULL,
    cargo character varying(50),
    criado_em timestamp without time zone DEFAULT now()
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: agendamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.agendamento (id_agendamento, data, hora, status, id_solicitacao, id_sala, criado_em) FROM stdin;
1	2026-03-10	08:00:00	Confirmado	2	1	2026-09-14 09:26:24.488478
\.


--
-- Data for Name: cirurgia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cirurgia (id_cirurgia, nome, descricao, complexidade, tempo_estimado, criado_em) FROM stdin;
1	Apendicectomia	Remoção cirúrgica do apêndice	Média	01:30:00	2026-09-14 09:26:24.482864
2	Colecistectomia	Remoção da vesícula biliar	Média	02:00:00	2026-09-14 09:26:24.482864
3	Artroplastia de Quadril	Substituição da articulação do quadril	Alta	03:30:00	2026-09-14 09:26:24.482864
\.


--
-- Data for Name: cirurgia_recurso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cirurgia_recurso (id_cirurgia, id_recurso, quantidade_necessaria, criado_em) FROM stdin;
1	1	1	2026-09-14 09:26:24.486182
1	2	1	2026-09-14 09:26:24.486182
1	3	1	2026-09-14 09:26:24.486182
3	1	1	2026-09-14 09:26:24.486182
3	2	1	2026-09-14 09:26:24.486182
3	4	1	2026-09-14 09:26:24.486182
\.


--
-- Data for Name: hospital; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hospital (id_hospital, nome, cnpj, endereco, telefone, email, criado_em) FROM stdin;
1	Hospital Central Vida Flow	12.345.678/0001-90	Av. Paulista 1000 - SP	(11) 3000-1000	contato@hospitalcentral.com	2026-09-14 09:26:24.44691
2	Hospital São Lucas	98.765.432/0001-10	Rua das Flores 500 - SP	(11) 3000-2000	contato@saolucas.com	2026-09-14 09:26:24.44691
\.


--
-- Data for Name: medico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medico (id_medico, id_hospital, crm, especialidade, nome, criado_em) FROM stdin;
1	1	CRM/SP 123456	Cirurgia Geral	Dr. Roberto Alves	2026-09-14 09:26:24.481337
2	1	CRM/SP 654321	Ortopedia	Dra. Carina Mendonça	2026-09-14 09:26:24.481337
\.


--
-- Data for Name: paciente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.paciente (id_paciente, nome, cpf, data_nascimento, telefone, tipo_sanguineo, criado_em) FROM stdin;
1	Carlos Eduardo Lima	111.222.333-44	1985-05-12	(11) 98765-4321	O+	2026-09-14 09:26:24.479827
2	Maria Fernanda Souza	222.333.444-55	1990-11-23	(11) 97654-3210	A-	2026-09-14 09:26:24.479827
3	João Pedro Santos	333.444.555-66	1978-02-04	(11) 96543-2109	AB+	2026-09-14 09:26:24.479827
\.


--
-- Data for Name: recurso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recurso (id_recurso, id_hospital, nome, categoria, quantidade, status, criado_em) FROM stdin;
1	1	Kit Anestésico Geral	Insumo	15	Disponível	2026-09-14 09:26:24.483734
2	1	Monitor Multiparâmetrico	Equipamento	8	Disponível	2026-09-14 09:26:24.483734
3	1	Bisturi Elétrico	Equipamento	4	Disponível	2026-09-14 09:26:24.483734
4	1	Prótese de Quadril Titânio	Prótese	3	Disponível	2026-09-14 09:26:24.483734
\.


--
-- Data for Name: sala_cirurgica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sala_cirurgica (id_sala, id_hospital, numero, tipo, status, criado_em) FROM stdin;
1	1	Sala 101	Geral	Disponível	2026-09-14 09:26:24.484892
2	1	Sala 102	Ortopedia	Disponível	2026-09-14 09:26:24.484892
\.


--
-- Data for Name: solicitacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitacao (id_solicitacao, data_solicitacao, prioridade, status, id_paciente, id_medico, id_hospital, id_cirurgia, criado_em) FROM stdin;
1	2026-03-01	Alta	Pendente	1	1	1	1	2026-09-14 09:26:24.487453
2	2026-03-02	Média	Aprovada	2	2	1	2	2026-09-14 09:26:24.487453
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, nome, cpf, email, senha, cargo, criado_em) FROM stdin;
\.


--
-- Name: agendamento_id_agendamento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.agendamento_id_agendamento_seq', 1, true);


--
-- Name: cirurgia_id_cirurgia_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cirurgia_id_cirurgia_seq', 3, true);


--
-- Name: hospital_id_hospital_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hospital_id_hospital_seq', 2, true);


--
-- Name: medico_id_medico_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medico_id_medico_seq', 2, true);


--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.paciente_id_paciente_seq', 3, true);


--
-- Name: recurso_id_recurso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recurso_id_recurso_seq', 4, true);


--
-- Name: sala_cirurgica_id_sala_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sala_cirurgica_id_sala_seq', 2, true);


--
-- Name: solicitacao_id_solicitacao_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitacao_id_solicitacao_seq', 2, true);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 1, false);


--
-- Name: agendamento agendamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agendamento
    ADD CONSTRAINT agendamento_pkey PRIMARY KEY (id_agendamento);


--
-- Name: agendamento agendamento_sala_data_hora_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agendamento
    ADD CONSTRAINT agendamento_sala_data_hora_key UNIQUE (id_sala, data, hora);


--
-- Name: cirurgia cirurgia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cirurgia
    ADD CONSTRAINT cirurgia_pkey PRIMARY KEY (id_cirurgia);


--
-- Name: cirurgia_recurso cirurgia_recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cirurgia_recurso
    ADD CONSTRAINT cirurgia_recurso_pkey PRIMARY KEY (id_cirurgia, id_recurso);


--
-- Name: hospital hospital_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hospital
    ADD CONSTRAINT hospital_cnpj_key UNIQUE (cnpj);


--
-- Name: hospital hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hospital
    ADD CONSTRAINT hospital_pkey PRIMARY KEY (id_hospital);


--
-- Name: medico medico_crm_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_crm_key UNIQUE (crm);


--
-- Name: medico medico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_pkey PRIMARY KEY (id_medico);


--
-- Name: paciente paciente_cpf_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_cpf_key UNIQUE (cpf);


--
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente);


--
-- Name: recurso recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_pkey PRIMARY KEY (id_recurso);


--
-- Name: sala_cirurgica sala_cirurgica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sala_cirurgica
    ADD CONSTRAINT sala_cirurgica_pkey PRIMARY KEY (id_sala);


--
-- Name: solicitacao solicitacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_pkey PRIMARY KEY (id_solicitacao);


--
-- Name: usuario usuario_cpf_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_cpf_key UNIQUE (cpf);


--
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: agendamento agendamento_id_sala_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agendamento
    ADD CONSTRAINT agendamento_id_sala_fkey FOREIGN KEY (id_sala) REFERENCES public.sala_cirurgica(id_sala);


--
-- Name: agendamento agendamento_id_solicitacao_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.agendamento
    ADD CONSTRAINT agendamento_id_solicitacao_fkey FOREIGN KEY (id_solicitacao) REFERENCES public.solicitacao(id_solicitacao);


--
-- Name: cirurgia_recurso cirurgia_recurso_id_cirurgia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cirurgia_recurso
    ADD CONSTRAINT cirurgia_recurso_id_cirurgia_fkey FOREIGN KEY (id_cirurgia) REFERENCES public.cirurgia(id_cirurgia);


--
-- Name: cirurgia_recurso cirurgia_recurso_id_recurso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cirurgia_recurso
    ADD CONSTRAINT cirurgia_recurso_id_recurso_fkey FOREIGN KEY (id_recurso) REFERENCES public.recurso(id_recurso);


--
-- Name: medico medico_id_hospital_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_id_hospital_fkey FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital);


--
-- Name: recurso recurso_id_hospital_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_id_hospital_fkey FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital);


--
-- Name: sala_cirurgica sala_cirurgica_id_hospital_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sala_cirurgica
    ADD CONSTRAINT sala_cirurgica_id_hospital_fkey FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital);


--
-- Name: solicitacao solicitacao_id_cirurgia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_id_cirurgia_fkey FOREIGN KEY (id_cirurgia) REFERENCES public.cirurgia(id_cirurgia);


--
-- Name: solicitacao solicitacao_id_hospital_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_id_hospital_fkey FOREIGN KEY (id_hospital) REFERENCES public.hospital(id_hospital);


--
-- Name: solicitacao solicitacao_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- Name: solicitacao solicitacao_id_paciente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente);


--
-- PostgreSQL database dump complete
--

\unrestrict rfayAAausqHrSs43flSaIlUKnJGuYLIRlrwk6jdSPDpzwgewl6dUmcVJYLATqkh

